### ISSUE TITLE
[epic] FAQ editable in be, displayed in fe

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1067]
The staff must be able to edit, directly from the back end the FAQ of the Tournesol project. This FAQ must then be displayed in the front end.

**to-do**
- [x] create new models in the back end
  - #1068
- [x] create the related public API to get all questions with theirs answers
  - [x] anonymous users must be able to access the FAQ
  - **(deferred)** the endpoint should take GET parameter `lang` to access the FAQ in a specific language
  - [x] without `lang` parameter the endpoint can try to match the request language, else fallback to English  
- [x] create a page in the front end that displays this FAQ
- [x] add links in the front end to make this page accessible
- [x] pin the FAQ somewhere in Discord?
  - the FAQ is now in the description of the two `questions` channel
