### ISSUE TITLE
EPIC: Dynamic website previews

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1080]
Website previews on social media are very impactful for sharing efficiently.

The website preview of Tournesol always shows the same image, which doesn't push people to share links to comparison pages or analysis pages. Even president @lenhoanglnh pastes his own screenshots when sharing Tournesol links

Goals:
- [x] Sharing a comparison page shows as image with the two thumbnails and one slider
- [x] Sharing an analysis page shows the thumbnail, video title (optional), Tournesol score, and best/worst criteria
  - we don't show the best/worst criteria yet 
- (optional) Sharing a search page shows the thumbnails and scores of the top videos (for that search?) 
- [x] Sharing any other page shows the default Tournesol Home page image

**Comment by amatissart** [comment]
I can see 3 approaches (but none of them are completely satisfying in my opinion :face_with_spiral_eyes:):

1. **Use Nginx** to serve dynamic content based on the requested URL:   
   * Quick and dirty (and limited, and fragile, and hard to extend) 
   * Possible via nginx "server side includes" (https://www.cambus.net/nginx-and-server-side-includes/)
   * Unclear whether it would enable to make API calls to fetch metadata from the database 

2. Deploy the "frontend" as a service to serve dynamic content instead of static files  

     **a. with limited SSR** (for HTML <meta> only)  
        For example with Express.js:  
        https://blog.logrocket.com/adding-dynamic-meta-tags-react-app-without-ssr
        With this approach alone, the dynamic tags would be visible by robots/crawlers but are not after client-side navigation (not a big deal?). 
        
     **b. With React server-side-rendering**
        Requires to replace create-react-app with a new framework, such as Next.js:  
        https://nextjs.org/docs/migrating/from-create-react-app  
        Significantly more complex to set up. Should all pages be rendered completely by the server? Probably not. The server may miss some context (authenticated pages, mobile version, etc.).

3. Serve dynamic HTML **with Django**  
   * No additional tool
   * Easy access to the data required to build the tags
   * Would probably require to duplicate logic between React-router and Django URLs, to build appropriate tags based on the requested URL.
