### ISSUE TITLE
Public dataset format

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1143]
I was looking at the public dataset. And I think there are a few things to improve. I let you discuss which to fix, suggest other ideas and decompose this in subtasks:

1 - the scores, if I'm not mistaken, should always be integers. But there are in the dataset a lot of badly rounded, non-integer numbers (e.g. 6.399999999999999). This is confusing, and it's not clear how to handle this. In my opinion, the comparison scores should always be integers and not floats.

![image](https://user-images.githubusercontent.com/47578089/191870715-73da211c-c36e-4cfd-aa57-db4d9c26494c.png)
2 - the weights are still always 1.0 (but the recent modifications in the voting rights may change this, it may be worth to wait if it is still prone to change)

3 - I guess knowing which comparisons are made from Sybil-resilient, trusted email addresses would be valuable, even though it may be deduced from the voting rights. Because the voting rights come from a complex, opaque calculation. And someone may prefer to rely on trusted email addresses which is a simple and clear-cut criteria for trust.

4 - I guess that dates (day of the comparison in the year, no need for higher precision) are not a too sensitive personal information for the comparisons that are already public. Moreover, if the content is currently sorted by date, it could already be indirectly inferred. It is really valuable in my opinions to have the dates in the dataset for a variety of reasons (detecting videos becoming obsolete, analyze how rating habits change, detect unsuspected patterns with machine learning...).

5 - think about what kind of sorting is best (by date, or by user, or by criteria...)

6 - As a later optimization, should we create a daily version of the dataset, that is stored in a file and can be downloaded without accessing the database ? It may be more efficient in the future. It could be done at the end of the Mehestan periodic job, which would help ensure the consistency between the dataset's raw data and Mehestan's calculated data.

7 - Should the estimated uncertainty be included in the dataset ?

8 - Should the dataset include some metadata (license, date of generation...) ?

9 - Should it be possible to download it in multiple formats (csv, pickle, hdf...) ?

10 - Making a series of Jupyter Notebooks for how to process this dataset , how to reproduce the results of our scientific reviews, and a few cool examples of things that can be done with, for example:

![image](https://user-images.githubusercontent.com/47578089/191873070-be8d0a7e-8c97-4e83-9f28-6b6eb8ab0efe.png)

11 - think about how to make the dataset generic for different polls (maybe there should be different download buttons for different polls)

12 - make a dataset with aggregated statistics (user-specific and/or non-user specific), including some reliable uncertainty metrics. So that you don't have to aggregate it yourself before using it, if you don't want to bother with comparison matrices. (e.g. imagine you want to painlessly make a ML model that predicts the score of a video based on the metadata (either the score for a specific user or the aggregated score)).

13 - There should maybe be a specific frontend page for the public dataset(s) (listing the different public datasets, explaining why they are important for research, adding a link to the scientific reviews...). It could be made accessible from  the links at the bottom left of the screen.

14 - Some of the user attributes that were deactivated for privacy reasons (e.g. nationality, moral philosophy, religion...) may actually be really valuable. But, if we want to reactivate it, we would need a big warning to users, so that they know that this data will appear in the database and that they should fill it only if they don't mind.

![image](https://user-images.githubusercontent.com/47578089/192071896-b1f2fd70-8ae6-40bc-8042-eb419d1de9da.png)

**Comment by lfaucon** [comment]
> 1 - the scores, if I'm not mistaken, should always be integers. But there are in the dataset a lot of badly rounded, non-integer numbers (e.g. 6.399999999999999). This is confusing, and it's not clear how to handle this. In my opinion, the comparison scores should always be integers and not floats.

This comes from the old version of Tournesol. I agree we should round them. We don't lose much.

**Comment by lfaucon** [comment]
> 2 - the weights are still always 1.0 (but the recent modifications in the voting rights may change this, it may be worth to wait if it is still prone to change)

This is indeed unused right now. This would be useful to let users express their level of confidence.
- [ ] Let's remove the column from the export as long as it is not meaningfully used.

**Comment by lfaucon** [comment]
> 3 - I guess knowing which comparisons are made from Sybil-resilient, trusted email addresses would be valuable, even though it may be deduced from the voting rights. Because the voting rights come from a complex, opaque calculation. And someone may prefer to rely on trusted email addresses which is a simple and clear-cut criteria for trust.

Thanks for the suggestion, we have done it by including users.csv in the export

**Comment by lfaucon** [comment]
> 4 - I guess that dates (day of the comparison in the year, no need for higher precision) are not a too sensitive personal information for the comparisons that are already public.

- [ ] #1299

**Comment by lfaucon** [comment]
> 6 - As a later optimization, should we create a daily version of the dataset, that is stored in a file and can be downloaded without accessing the database ? It may be more efficient in the future. It could be done at the end of the Mehestan periodic job, which would help ensure the consistency between the dataset's raw data and Mehestan's calculated data.

- [ ] #1267

**Comment by lfaucon** [comment]
> 7 - Should the estimated uncertainty be included in the dataset ?

- [ ] Document it in the export's readme and include the uncertainties

**Comment by lfaucon** [comment]
> 8 - Should the dataset include some metadata (license, date of generation...) ?

Yes!
We now include a readme file to document the different tables.

- [ ] Include a metadata export including the date
- [ ] Include a license file

**Comment by lfaucon** [comment]
> 9 - Should it be possible to download it in multiple formats (csv, pickle, hdf...) ?

Other comment by @glerzing : "7z may be more performant for compression"

Sticking to csv and zip is friendly for compatibility with all systems. As performance is not soon to be an issue I'd recommend not to change it for now.

**Comment by lfaucon** [comment]
> 10 - Making a series of Jupyter Notebooks for how to process this dataset , how to reproduce the results of our scientific reviews, and a few cool examples of things that can be done with, for example:

Great idea. We have also developped a streamlit app (see https://github.com/tournesol-app/tournesol/tree/main/data-visualization)
I agree on providing notebooks for each publications to reroduce the results.

**Comment by lfaucon** [comment]
> 11 - think about how to make the dataset generic for different polls (maybe there should be different download buttons for different polls)

We decided to not share the data about the French presidential election. It's not sure whether future poll would be shared publicly or not. Let's reconsider this question at this moment.

**Comment by lfaucon** [comment]
> 12 - make a dataset with aggregated statistics (user-specific and/or non-user specific), including some reliable uncertainty metrics. So that you don't have to aggregate it yourself before using it, if you don't want to bother with comparison matrices. (e.g. imagine you want to painlessly make a ML model that predicts the score of a video based on the metadata (either the score for a specific user or the aggregated score)).

Agreed! We have been and are slowly working on adding the values computed by the ML algorithms.

**Comment by lfaucon** [comment]
> 13 - There should maybe be a specific frontend page for the public dataset(s) (listing the different public datasets, explaining why they are important for research, adding a link to the scientific reviews...). It could be made accessible from the links at the bottom left of the screen.

Thanks for the re commendation. We added a section on the homepage for this.

**Comment by lfaucon** [comment]
> 14 - Some of the user attributes that were deactivated for privacy reasons (e.g. nationality, moral philosophy, religion...) may actually be really valuable. But, if we want to reactivate it, we would need a big warning to users, so that they know that this data will appear in the database and that they should fill it only if they don't mind.

We don't have short term plans to re-activate this, but it may come later when we are well prepared

**Comment by lfaucon** [comment]
to-do @lfaucon  create tickets for remaining tasks and close this large ticket

**Comment by aidanjungo** [comment]
Separate issue have been created for the two remaining task:

- #1396 
- #1397
