### ISSUE TITLE
Notify user more regularly

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#1206]
The aim would be to be able to notify Tournesol user more regularly about new features and encourage them to make more comparisons.
 
- [x] Change privacy policy to describe the newsletter mechanism (opt-out) and few notification email (opt-out)
  - It has been described in the Terms of Service https://github.com/tournesol-app/tournesol/pull/1511
- [x] Add term of services #1452 
- [x] Send mail to all user to warn about the change of privacy policy
  - done the  2023-06-29 
- [x] Add these options in profile settings when #1277  is ready
  - Added by https://github.com/tournesol-app/tournesol/pull/1647 
- [x] Add language preferences in settings when #1277  is ready
  - https://github.com/tournesol-app/tournesol/issues/1663 
- [x] Add these options at registration
  - research and new features notifications are added by https://github.com/tournesol-app/tournesol/pull/1657
  - the language field is still missing
- [x] #1677
- [x] Check newsletter mechanism (how to update Sendinblue mailling list update?)

This is the main issue, but it could be breakdown into several small issues.

Idea:
- In the reminder mail we send to users, we could add something like:
   > The video "XYZ" that your rate well, as been shown to n people last month

**Comment by GresilleSiffle** [comment]
In the Preferences page we recently added two settings for the email notifications:
- research studies and surveys about the project
- new features

![capture](https://github.com/tournesol-app/tournesol/assets/39056254/2ec9b556-bb89-4c51-8001-57d8cd004532)

We still need to allow the users to select their preferred language between English en French.

**Comment by GresilleSiffle** [comment]
The PR #1664 adds the preferred language setting in the Preferences page.

![capture](https://github.com/tournesol-app/tournesol/assets/39056254/f5649b55-490d-4d30-aefb-8ba14f1caaab)
