### ISSUE TITLE
Epic: UI Settings page

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#1277]
- [x] Rate later:  min comparisons before removing videos
  - [x] back end #1294  
  - [x] front end #1409 
- [x] Comparison: optional criteria to disable/enable/reorder
  - [x] back end #1410 
  - [x] front end criteria page #1411 
  - [x] front end settings #1412 
- [x] Recommendations: default filters
  - [x] back end #1435
  - [x] front end recommandation page
  - [x] front end settings
- [x] Recommendations: language in both frontend and extension: https://github.com/tournesol-app/tournesol/issues/1560
- [x] #1725
- Comparison: behavior of "Auto"
  - moved in the milestone https://github.com/tournesol-app/tournesol/issues/1673

**Comment by lfaucon** [comment]
> What would be the requirement of the last task, [ ] Comparison: behavior of "Auto" ? Was some part of it worked on in https://github.com/tournesol-app/tournesol/pull/1425 ?

@abhiram11 #1425  was a nice refactor but it did not change the behavior. Because we are now working on a User Settings page where users can configure how they prefer to use Tournesol. One of these preferences would be customizing what the "Auto" button does.

**Comment by abhiram11** [comment]
> > What would be the requirement of the last task, [ ] Comparison: behavior of "Auto" ? Was some part of it worked on in #1425 ?
> 
> @abhiram11 #1425 was a nice refactor but it did not change the behavior. Because we are now working on a User Settings page where users can configure how they prefer to use Tournesol. One of these preferences would be customizing what the "Auto" button does.

I see, thanks for the elaboration !

**Comment by GresilleSiffle** [comment]
Recently we discover that creating a setting for the default languages of the recommendations will require more work than expected.

Here are the challenges:
1. there is already a mechanism that controls the default languages (the filter on the recommendations page)
2. the value of this filter is also used by the extension
3. this filter can be used by anonymous users

If we add a new setting in the Preferences page we will have two mechanisms controlling at the same time the language. One filter on the recommendations page and one field in the preferences page, which will be confusing to use, and to maintain. If we add a new setting **and** if we remove the behaviour of the filter, then we will have a coherent behaviour, easy to maintain but anonymous users won't have the possibility to fully use the extension (because they won't be able to control the recommendation languages).

We planed to address this problem by creating a Preferences page in the extension (see https://github.com/tournesol-app/tournesol/issues/1560) that will work for authenticated and anonymous users.

**Question:** is the feature "preferences in the extension" still part of this milestone? or do we want to create a new milestone?

On my side, I have a little preference for creating a new milestone dedicated to the extension. Mainly to avoid having this feeling of never ending milestones. The actual milestone User settings could be dedicated to the web site part, which is nearly finished depending on how we want to address the behaviour of the Auto button.

**Comment by GresilleSiffle** [comment]
**Question (2)** About the behaviour of the Auto button.

I'd like to discuss about it so that we can all have a clear vision of what we try to achieve.

Here are the featured we already talked about more or less informally:
- (a) allowing the users to control the pools of videos used by Auto (rate-later / recently compared / to-connect / monthly global best)
- (b) allowing the users to turn on/off the automatic click on Auto

About (a), on one hand I really like the feature because it will give more control to the user on what's going when clicking on Auto. On the other hand, even with this feature I think it might still feel a bit hazardous to click on Auto. Because it will not be possible to ask for a random video from the rate-later only, if the setting is configured with rate-later / to-connect. It will not be possible to ask for a random video from the rate-later only then from the to-connect only, without updating the preferences between each click.

If often find myself in the situation where I want a random video from my rate-later list in one selector and a random videos from the monthly global best in the other selector.

Instead of (a), or in addition to (a), I'd like to propose a solution that will help users to pick a video: in the video selector, under each tab, display a button [random] or  [auto-pick] that will select a random video from the currently opened list (not limited to the 20 displayed videos, it will get a random video from the whole database).

This proposition is not related to the user settings, but have overlapping goals:
- helping the users to get videos to compare
- not overloading the comparison UI with new buttons (by taking advantage of the video selector)
- give the users more control on what is going on

What you do think @lfaucon @aidanjungo @amatissart  about the following plan:
- first, improving the video selector with this new random buttons
- then, create a setting to control the behaviour of the Auto button
- finally, add more settings if we have more ideas

**Comment by lfaucon** [comment]
A version (a*) is slightly different: the user selects pools for suggesting videos, but also give them priorities. So you would be able to configure "random from rate-later, otherwise to-connect" 

> If often find myself in the situation where I want a random video from my rate-later list in one selector and a random videos from the monthly global best in the other selector.

This is your very unique experience.

Mine is: "Start. with first video from rate later, (x) compare against to-connect until 3 comparison, then rate-later, then loop back to (x)"

=> I would love to collect 5-6 similar descriptions of their process from the community on discord. Could you ask and collect the few different processes to be discussed in an upcoming brainstorm/call?

It seems that "behavior of auto" and "redesign of selector" are intertwined features, so let's design/discuss them together on a Tuesday evening?

**Comment by GresilleSiffle** [comment]
Thanks for your answers : )

> This is your very unique experience.

Yes you are right, we should not design features that match only one very specific use case. In our case I still think being able to select precisely from which pool the videos come from make possible a lot of different use cases that could be useful for different kind of users.

For instance:
- select only videos from the rate-later list
- select one video from the rate-later list, and one from the to connect tab
- select videos that has been compared at least one time, but less than the `auto_removal` setting
- more generally selecting one video from any list and another from any list

Today we give this possibility to the users but we limit them to the first 20 videos of each pool. Not because we thought it was the best design decision, but because it was good enough for the first implementation of the video selector.

A second argument that makes me think a random button for each tab is a good feature: those buttons won't shadow the main Auto button, because they are not displayed by default. They don't constraint the users to adopt a specific behaviour and because of this I think they can be seen as an enhancement of the video selector, rather than a replacement of our suggestion mechanism.

> I would love to collect 5-6 similar descriptions of their process from the community on discord. Could you ask and collect the few different processes to be discussed in an upcoming brainstorm/call?

That would be great, let's do this. We can even collect data thanks to our mailing list now.

> It seems that "behavior of auto" and "redesign of selector" are intertwined features, so let's design/discuss them together on a Tuesday evening?

Good idea.
