### ISSUE TITLE
[back] feat: create an API to interact with the user settings

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1293]
### technical specifications

The users' settings are JSON objects representing the users' preferences. Each key is a setting used by the back end or the front to modify certain of their behaviours. A user has exactly one set of personal settings.

Example:
```json
{
  "frontend.alpha_ui": false,
  "frontend.beta_ui":  true,
  "rate_later.auto_remove": 4
}
``` 

(The namespaces are here to make the settings more understandable, some of them are front end only, some of them might be related to a specific part of the API, etc.)

**Q1 Where to store the settings?**

The settings can be either saved as a new `JSONField` in the currnet `User` model, or in a related one-to-one model. For performance reason I propose to directly alter the current `User` model. It may also ease retrieving the settings during the log in process.

This field could could be `blank=True`, `null=False` and `default=dict`.

**Q2 Where to store the settings serializers and API?**

Short answer: saving everything in `core` is not perfect but looks simple and good enough.

The API and its related tests could go in the folder `core`, because its behaviour will be rather generic whatever the content of the settings: receiving a JSON input, using a serializer to validate the data and saving them, etc.

Concerning the serializer(s) it's a bit different. I think it depends on how independent and re-usable we want the API and the front end to be. It depends on how easy we want for a fork of Tournesol to re-use the back with a completely new UI with its own set of user settings.

Some settings will be used only by the front end, making them specific to the UI and useless for our API. If we want to avoid writing the Tournesol front end's specific keys in the supposedly generic folder `core` of our API, maybe we would like to move both the API definition and its serializer(s) elsewhere, like in the `tournesol` folder. Nevertheless this is also a very imperfect solution. Without a proper way to configure the settings in the back end without hard coding them in, it seems like choosing the right folder to store the specific serializer(s) just moves the problem from one place to another.

**to-do**

Create the routes
- [x] `GET /users/me/settings`
- [x] `PUT /users/me/settings`
  - replace the complete user settings by the new JSON provided 
- [x] `PATCH /users/me/settings`
  - replace only the provided keys

Check how the API can return the user settings after a login (it shouldn't be complex if the settings are a field of the `User` model).

**Comment by GresilleSiffle** [comment]
Here is the current path I'm following. The objective is to:
- allow the users to have different settings per poll
- allow the polls to have their own specific settings
- allow the platform to have global poll-agnostic settings

```json
{
  "common": {
    "email_notification__platform_updates": true,
    "email_notification__studies": true,
    "email_notification__monthly_top10": false,
    "website_ui__beta": true
  },
  "videos": {
    "rate_later__auto_remove": 4,
    "recommendations__hide_compared_videos": false
  },
   "presidentielle2022": {
    "rate_later__auto_remove": 3
  } 
}
```
