### ISSUE TITLE
Improve HTTPS configuration

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#1439]
- [x] Disable deprecated TLS ciphers (CBC based)
Probably in this nginx configuration:
https://github.com/tournesol-app/tournesol/blob/845634e76e176448b81793cd956286b27e649ec5/infra/ansible/roles/nginx/templates/nginx.conf.j2#L35-L35

- [x] Higher HSTS max-age: 180 days instead of `max-age=300`

**Comment by GresilleSiffle** [comment]
**to-do**
- [ ] apply the HSTS max-age on Grafana and Plausible
