### ISSUE TITLE
[back][front] refactor: the JSON response of the rate-later API

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1466]
**subtask of** https://github.com/tournesol-app/tournesol/issues/606

---

Do do not forget:

- [ ] extension update strategy
- [ ] retro compatibility url

---

**W.I.P.**
- [ ] better describe the back end part
- [ ] better describe the front end part
- [ ] double check the JSON format with the team

Rework the response of the rate-later API to match the following format (see the original discussion in https://github.com/tournesol-app/tournesol/issues/606#issuecomment-1308348588)

```json
{
  "entity": {
    "uid": "string",
    "type": "video",
    "metadata": {
      "additionalProp1": "string",
      "additionalProp2": "string",
      "additionalProp3": "string"
    }
  },
  "poll": {
    "name": "string",
  },
  "invididual_rating": {
    "is_public": true,
    "n_comparisons": 0
  },
  "collective_rating": {
    "tournesol_score": 0,
    "n_comparisons": 0,
    "n_contributors": 0
  },
  "rate_later_metadata": {
    "created_at": "2022-11-08T13:47:39.480Z"
  }
}
```

**Comment by GresilleSiffle** [comment]
In my  spec, the `poll` key doesn't seem to be required. We always ask for rate-later items in the scope of a poll, so the API consumer already knows to which poll the items are attached.
