### ISSUE TITLE
[back] refactor: Unsafe should be handled in the backend 

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1686]
### To-do
- [ ] The backend should have a unique centralized mechanism to determine if an entity is safe or unsafe
- [ ] The backend serializer for entities should include in API response metadata concerning the safe status of entities (see proposition below). 
- [ ] The entity card in the frontend should display the grey sunflowers and explaination tooltips based on the backend responses.

### Proposition
The frontend and backend should maintain a list of keywords/reasons that make entity unsafe.

The serializer output could roughly look like:
```
{
    "uid": "yt:ePU32cKdtPs",
    "tournesol_score": 42,
    "unsafe": {
        status: bool
        reasons: List[Enum]
    }
}
```
