### ISSUE TITLE
(feat) Public data

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#274]
# Context

This is a rather large feature. 

At any time this list of tasks can be split into multiple tickets. It is also recommended to split the work in as many independent units as possible

In order to make this feature simple both for users and for implementation we want only to enable that a user can specify "Everything about video V is private". This means a Comparison will be public if it was marked as public for both videos.

# Subtasks:
- [x] Update models to specify an attribute `is_public` per user & video. This could either re-use the ContributorRating model or use a new model
- [x] Open and API endpoint or modify an existing one enable fetching and updating the `is_public` information
#315 
#320

- [x] Add interface on the frontend that allows users to control the is_public for their list of videos. It would be useful if users can find their list of private & public video and if user can choose to make all their video public or all their video private with a single interaction.
Partially addressed in #322 

- [x] Deprecate unused code related to making comparison and aggregated ratings public

- [x] An api endpoint and a link somewhere on the frontend to download the database of all public comparisons, contributor ratings and videos (with criteria scores)
