### ISSUE TITLE
Update logo before public announcement

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#338]
I think the new Tournesol logo should be changed on:

- [x] Github
- [x] Discord
- [x] Wiki
- [x] Twitter
- [x] Twitter bots (fr/en)
- [x] LinkedIn
- [x] Firefox extension store
- [x] Chrome extension store
- [x] Paypal
- [x] Instagram
