### ISSUE TITLE
Automate reminders for monthly chores

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#407]
For example: 

- [ ] upgrading packages on prod
- [ ] testing back-up restoring
- [ ] Testing provisioning a server from scratch
- [ ] Testing experience of a new user (creating account, tutorial, first comparisons, ...)

**Comment by amatissart** [comment]
* testing VM provisioning
* back-up restoring from AWS

**Comment by amatissart** [comment]
* [ ] rotating admin credentials and shared secrets

**Comment by GresilleSiffle** [comment]
- [ ] check and update back end's requirements when relevant
  - [ ] Django
  - [ ] Django REST Framework
  - [ ] etc.

**Comment by lfaucon** [comment]
- [ ] reviewing milestones

**Comment by amatissart** [comment]
- [ ] create snapshot of production VM on Vultr

**Comment by aidanjungo** [comment]
To summarize all the task we should have and their frequencies:

### Every month

- [ ]  Reviewing milestones

### Every 3 months

- [ ] Upgrading packages on prod
- [ ] Check and update back end's requirements when relevant (Django, Django REST Framework, etc.)
- [ ] Testing back-up restoring
- [ ] Back-up restoring from AWS
- [ ] Testing provisioning a server from scratch
- [ ] Testing VM provisioning
- [ ] Testing experience of a new user (creating account, tutorial, first comparisons, ...)

### Every year

- [ ] Rotating admin credentials and shared secrets


@amatissart @lfaucon @GresilleSiffle do you have other idea, I will use the list to implement the feature.

**Comment by lfaucon** [comment]
Created the to-do list for monthly chores in our Retrospective MIRO board
