### ISSUE TITLE
[EPIC] Add account validation through vouching mechanism to distribute trust to users who do not belong to trusted entities

### ISSUE THREAD

**Issue by BerangereColbois** [tournesol-app/tournesol#720]
- [x] [back] create structure to support the vouching mechanism
      * store connections between users, and local trust values between two peers 
      * store list of users trusting and trusted by each user
- [x] [back] compute global trust values per users, based on the [EigenTrust algorithm](ilpubs.stanford.edu:8090/562/1/2002-56.pdf). This value can be used to know how much we trust every user later on.
- [x] [front] modify sign up and profile page accordingly, to get and display all information listed above
- [x] [front] add a vouching system, where each user can vouch for other users, by selecting how much they trust the user,  Modify the profile page by adding the following fields :
      * list of users the user vouched for
      * list of users who vouched for this user
- [x] #1178
- [x] [back] #1071 
- [x] [back] refactor: On the user model "voting-right" -> "trust score". Rename the column in the addtional file added to the public dataset.
- [x] #1176
- [x] #1060
- [ ] UNSURE: Voting rights displayed on user profile page should not be the trust score, but the average voting rights on all their rated videos displayed as a percentage.
