### ISSUE TITLE
[front] feat: replace analysis button by a navigation link when a thumbnail / video title is clicked

### ISSUE THREAD

**Issue by adrausch** [tournesol-app/tournesol#931]
**to-do**

- [x] add the feature
  - see: #942 
- [x] add e2e tests 
  - see: #957
- [x] create an issue to completely remove the `<VideoList>` (and the `<VideoCard>`)
  - see: #975 
- [x] check with the team if the analysis button should be removed
  - see: #960

**Comment by GresilleSiffle** [comment]
I like the idea of watching videos directly from the analysis page, as it mimics the navigation in YouTube :+1: 

There is one place in the application where I personally like the current behaviour is the comparison page. As a contributor, I like to be able to start a video directly from the comparison page, to either adjust my ratings or to refresh a bit my memories. I really like this feature as it makes the comparison experience comfortable, I don't need to open new tabs to start the videos, the UI gives me all I need to do it.

Do you have similar experiences @adrausch @amatissart @aidanjungo @lfaucon ? Do you think this is a good feature to keep?

My suggestion for this issue would be:
- thumbnails and titles are link to the analysis page
- except on the analysis page itself and the comparison page

**Comment by GresilleSiffle** [comment]
> Now that you raise the question, yes it can be deleterious for the navigation on Tournesol.
> Maybe the alternative could be to make clickable the title of the video only? What do you think?

It's indeed an alternative.

I like the idea of having a "strong" analysis page full of features. Making the thumbnails clickable will make the page inescapable, which is a good UX in my opinion.

I'm in favor of clickable thumbnails, but not on the comparison page.

**Comment by lfaucon** [comment]
> when someone arrive on the analysis page, we don't know if he wants the video to be played on just see the analysis stats (we might guess they want an auto-play if they clicked on the thumbnail)

When someone clicks the video thumbnail it is quite clear the goal is to play the video

> So we have to choice to make the users click to play a video with sound, or to make the users lick to enable the sound of an already playing video, which seems to be equivalent in term of effort.

If it is really this choice, then I agree that keeping the no-autoplay is best

Although I don't believe that we don't have another option. Typically, the user stays on our single page app, then clicks a thumbnail of a video to play it. This is not really "autoplay" as much as "play the video when user clicks it". I think some tricky management of the ReactPlayer component when navigating to the analysis page could make playing the video directly fully working as expected. But I expect it would be tricky, and it is just a small QoL feature, so let's not prioritize it.
